{% set name = "yambo" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yambo-code/yambo/archive/refs/tags/{{ version }}.tar.gz
  sha256: eb41e83df716eb87261cf130ffe7f930e7dc2e123343d47b73d5a3c69fea7316

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    - m4
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - wget
    - openmpi
    - libblas
    - liblapack
    - fftw * *openmpi*
    - hdf5 1.10 *openmpi*
    - libnetcdf 4.7 *openmpi*
    - netcdf-fortran 4.5 *openmpi*
    - zlib
    - scalapack
    - libxc * *cpu*
    - petsc * *complex*
    - slepc * *complex*
  host:
    - openmpi
    - libblas
    - liblapack
    - fftw * *openmpi*
    - hdf5 1.10 *openmpi*
    - libnetcdf 4.7 *openmpi*
    - netcdf-fortran 4.5 *openmpi*
    - zlib
    - scalapack
    - libxc * *cpu*
    - petsc * *complex*
    - slepc * *complex*
  run:
    - openmpi
    - fftw
    - zlib
    - libcurl
    - scalapack
    - libblas
    - liblapack
    - hdf5
    - libnetcdf
    - netcdf-fortran
    - petsc
    - slepc

test:
  commands:
    - yambo --help

about:
  home: http://www.yambo-code.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Open-source many-body perturbation theory and time-dependent density functional theory
  description: |
    YAMBO implements Many-Body Perturbation Theory (MBPT) methods (such as GW and BSE) and Time-Dependent Density Functional Theory (TDDFT), which allows for accurate prediction of fundamental properties as band gaps of semiconductors, band alignments, defect quasi-particle energies, optics and out-of-equilibrium properties of materials.
    The code resorts to previously computed electronic structure, usually at the Density Functional Theory (DFT) level and for this reason it is interfaced with two of the most used planewave DFT codes used in scientific community, Quantum ESPRESSO and Abinit.
  doc_url: http://www.yambo-code.org/
  dev_url: http://www.yambo-code.org/

extra:
  recipe-maintainers:
    - ltalirz
    - nicspalla
