{% set name = "yambo" %}
{% set version = "5.3.0" %}
{% set sha256 = "47b7591b31f833f371f6538050ac27e66d7ddb6f82034cad0100a8f02b3d8072" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/yambo-code/yambo/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
    - make
    - m4
    - libgomp  # [linux]
    - llvm-openmp  # [osx]
    - wget
    - openmpi
    - libblas
    - liblapack
    - fftw * *openmpi*
    - hdf5 1.14 *openmpi*
    - libnetcdf 4.9 *openmpi*
    - netcdf-fortran 4.6 *openmpi*
    - zlib
    - scalapack
    - libxc * *cpu*
    - petsc * *complex*
    - slepc * *complex*
  host:
    - openmpi
    - libblas
    - liblapack
    - fftw * *openmpi*
    - hdf5 1.14 *openmpi*
    - libnetcdf 4.9 *openmpi*
    - netcdf-fortran 4.6 *openmpi*
    - zlib
    - scalapack
    - libxc * *cpu*
    - petsc * *complex*
    - slepc * *complex*
  run:
    - openmpi
    - fftw
    - zlib
    - libcurl
    - scalapack
    - libblas
    - liblapack
    - hdf5
    - libnetcdf
    - netcdf-fortran
    - petsc
    - slepc

test:
  commands:
    - yambo --help

about:
  home: http://www.yambo-code.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Open-source many-body perturbation theory and time-dependent density functional theory
  description: |
    YAMBO implements Many-Body Perturbation Theory (MBPT) methods (such as GW and BSE) and Time-Dependent Density Functional Theory (TDDFT), which allows for accurate prediction of fundamental properties as band gaps of semiconductors, band alignments, defect quasi-particle energies, optics and out-of-equilibrium properties of materials.
    The code resorts to previously computed electronic structure, usually at the Density Functional Theory (DFT) level and for this reason it is interfaced with two of the most used planewave DFT codes used in scientific community, Quantum ESPRESSO and Abinit.
  doc_url: http://www.yambo-code.org/
  dev_url: http://www.yambo-code.org/

extra:
  recipe-maintainers:
    - ltalirz
    - nicspalla
